# Generated by Django 3.1.6 on 2021-02-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('PublishDate', models.DateTimeField(verbose_name='Published date')),
                ('domaine', models.CharField(max_length=70)),
                ('photo', models.BinaryField()),
            ],
        ),
    ]
