# Generated by Django 3.1.6 on 2021-02-22 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='PublishDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 22, 17, 36, 52, 645830), verbose_name='Published date'),
        ),
    ]
